### ISSUE TITLE
JTAG CN1 Pin Out / Marking

### ISSUE THREAD

**Issue by jsavage** [softerhardware/Hermes-Lite2#106]
Hi, just a quick note to suggest silk screen marking the top side of the board for Pin 1 of CN1.
I worked it out from the schematics and identifying R3 and R4 on the back of the board but if there is not significant addition to cost I sure it would help some.  
Interestingly, my Rev B programmer cable goes over the Altera when Pin 1 is aligned whereas on the [youtube video](https://www.youtube.com/watch?v=5m2kUmod0yQ&feature=youtu.be) the cable lies the other direction.   
![image](https://user-images.githubusercontent.com/189524/53056480-40069e80-34a3-11e9-941c-d03349769bf7.png)

I appreciate the cutout is shown but not all headers are shaped as anticipated.

**Comment by softerhardware** [comment]
Added pin 1 identifier to silkscreen.
