### ISSUE TITLE
Hardware: Missing DC blockers for RF Switch PE4259

### ISSUE THREAD

**Issue by rfrht** [softerhardware/Hermes-Lite2#110]
Hi there, congratulations for the project!

After reviewing the schematics, I have found that U10 and U11 (PE4259 RF switches) has no DC blockers.

As per PE4529 datasheet, verbatim:
"All RF pins must be DC blocked with an external series capacitor or held at 0 VDC."

Might be related to Issue #46.

Just a heads up and hope that helps!

73s de PY2RAF.

**Comment by softerhardware** [comment]
Hi,

Thanks for the feedback. The output of the opamp is DC biased, but there is a blocking capacitor between the opamp and the PE4259. The other connections to the PE4259 are not DC biased (at 0VDC) so do not need a blocking capacitor. There have been no issues here now in almost 200 units. We followed this application note: https://www.psemi.com/pdf/app_notes/an27.pdf

73,

Steve
kf7o
