### ISSUE TITLE
Gateware: Provide Queue Info and Other Feedback

### ISSUE THREAD

**Issue by softerhardware** [softerhardware/Hermes-Lite2#120]
See this thread: https://groups.google.com/d/msg/hermes-lite/vkkFb6cuvy8/suqbxn5oCQAJ

**Comment by softerhardware** [comment]
Have a mode to synchronize the TX on/off with the data stream, not async like CW: https://groups.google.com/d/msg/hermes-lite/e0X2JrogGMo/0pc8JdqvAQAJ

**Comment by csylvain** [comment]
does obtaining the same information remotely that is conveyed by the LEDs count as "other feedback"?

**Comment by softerhardware** [comment]
This is in latest gateware:
https://github.com/softerhardware/Hermes-Lite2/wiki/Protocol#base-memory-map-when-ack0
