### ISSUE TITLE
PTT Hangs in CW Mode Using Quisk 4.1.40

### ISSUE THREAD

**Issue by WN7T** [softerhardware/Hermes-Lite2#124]
Hello. 
When using Quisk version 4.1.40 on a Windows10 laptop and sending CW, the PTT hangs on TX and does not return to receive mode unless I either cycle the "Spot" button (hit it twice), or terminate Quisk. This bug occurs on both a build 8 HL2 with Code Version "68" installed and on a build 9 HL2 with Code Version "67" installed. 
Cheers,
Paul WN7T

**Comment by softerhardware** [comment]
Thanks. I try to fix this this weekend.

**Comment by WN7T** [comment]
Thank you, Steve, for all your hard work and diligence supporting this project.

**Comment by softerhardware** [comment]
Fixed in latest gateware.
