### ISSUE TITLE
Small schematic updates

### ISSUE THREAD

**Issue by in3otd** [softerhardware/Hermes-Lite2#137]
On page 7 of the H-Lv2 schematic the text notes referencing "pin 1" for the EXTTR and INTTR signals should be corrected (maybe simply referencing "INTTR" and "EXTTR") as they now go to other connectors/pins.

Also in the [same directory](https://github.com/softerhardware/Hermes-Lite2/tree/master/hardware/hl) the files [frontsilk.pdf](https://github.com/softerhardware/Hermes-Lite2/blob/master/hardware/hl/frontsilk.pdf) and [backsilk.pdf](https://github.com/softerhardware/Hermes-Lite2/blob/master/hardware/hl/backsilk.pdf) are for the old beta2 build and should be updated or deleted.

**Comment by softerhardware** [comment]
Done
