### ISSUE TITLE
linhpsdr stuttering tx audio

### ISSUE THREAD

**Issue by m5evt** [softerhardware/Hermes-Lite2#140]
Gateware 20190907 and beyond causes linhpsdr to transmit stuttering audio. Inspection of packets in wireshark confirms a systematic pattern where some tx packets are sent from linhpsdr with a time gap of up to 23 ms between packets.

see https://groups.google.com/d/msg/hermes-lite/SjzO6YE28EY/Qk7HMe-TAgAJ

**Comment by softerhardware** [comment]
M5EVT has fixed this in linhpsdr. The latest changes to the TX buffer latency should help too.
