### ISSUE TITLE
The fan does not turn off

### ISSUE THREAD

**Issue by lb1hi** [softerhardware/Hermes-Lite2#142]
_..Observation - not a bug because it is beta phase_
The fan does not turn off even when the temperature has dropped if the control software is off. 
Restarting the control program or restarting HL2 fixes the problem and the fan turns off.

PS. If the control software (Quisk) remains switched in RX, the fan switches off as planned at 30 degrees.

PS.2 Additionally suggestion is to raise the switch-off temperature to 35 degrees. 

73, Jozef

**Comment by softerhardware** [comment]
This has been fixed starting with 71p0 and later.
