### ISSUE TITLE
Undocumented behaviour when ADDR 0x0 DATA 0x7 is set

### ISSUE THREAD

**Issue by m5evt** [softerhardware/Hermes-Lite2#145]
Setting this bit causes IQ packets to become corrupted in rx. 

In protocol 1 this is Common Mercury Frequency and is used for diversity rx to lock RX1 and RX2 frequency. I propose the HL2 does not need to use this bit. See https://groups.google.com/d/msg/hermes-lite/FYS15G-tWhs/SnOt-8KDAwAJ

Behavior of this bit should either be documented or left such that setting this bit has no undesired effect?

**Comment by softerhardware** [comment]
Code in git main now ignores this bit. Will be in next gateware release.
