### ISSUE TITLE
After changing to the cicrx.rbf gateware gain stays on 100 rbfs for all and any receiver

### ISSUE THREAD

**Issue by waterwin** [softerhardware/Hermes-Lite2#159]
I uploaded the alternative gateware for the 10 RX slices with SparkSDR and Quisk.
Both give the same result when trying to run a receiver in SparkSDR.
On all frequencies, in all bands the same spectrum and white noise only.
Gain stays on 100 rbfs in MAX and OFF modes.

Roll back to main.rbf works and back to 4 RX slices is working.

What else can I try to get to a working 10 RX slice Hermes Lite V2 ?

In the SparkSDR error log I can see that in the programming step the Erase always fails and I also see that Main is a little bigger than Cicrx. Will this non erase issue leave wrong bits in the system?

**Comment by softerhardware** [comment]
Hi,

Can we move this to the Google group?
hermeslite.com

Are you running with RX bandwidth of 192kHz? To fit 10 receivers, we have
to simplify things and run at 192kHz with only CIC filtering, so only ~40%
of the bandwidth is usable.

73,

Steve
kf7o

**Comment by waterwin** [comment]
Thanks for your quick reaction Steve,
I tried all bandwidth possibilities.
The issue is there when starting 1 receiver, or 2, or 3 ..... or 10
I'll copy the info to the group and do a second try today with Quisk as well

**Comment by softerhardware** [comment]
I have used this 10 CIC gateware just today with no gain issues. 
https://github.com/softerhardware/Hermes-Lite2/tree/master/gateware/bitfiles/stable/20201212_72p8/variants/hl2b5up_cicrx

I think this has been solved on the Google Group so am closing the issue.
