### ISSUE TITLE
Add 10Mhz external clock source input and output

### ISSUE THREAD

**Issue by K7MDL2** [softerhardware/Hermes-Lite2#161]
Enable option to use a 10Mhz external reference clock source on Clk1 input.  Additionally configure Clk2 for 10Mhz output, useful for daisy chaining 10Mhz source to a transverter LO or test equipment.  See new function added def enable_cl1_cl2_10mhz().  It is also called at startup after discover at bottom of file.

[hermeslite.zip](https://github.com/softerhardware/Hermes-Lite2/files/6795844/hermeslite.zip)

**Comment by softerhardware** [comment]
Hi,

Thanks! I merged in the changes from your hermeslite.zip file. I commented out the automatic clock setting at the bottom as not everyone will want to do that when starting the script. We can add an argument to the script if you want a way to automatically use 10MHz.

73,

Steve
kf7o
