### ISSUE TITLE
Firmware: Port VNA support in HL1.22 to HL2

### ISSUE THREAD

**Issue by softerhardware** [softerhardware/Hermes-Lite2#19]
The current HL2 RTL forked before Jim added better VNA support. Backport Jim's changes into HL2.

**Comment by jimahlstrom** [comment]
I will do this as soon as I have the RTL and a working board.

**Comment by softerhardware** [comment]
Jim Ahlstrom, N2ADR, has done this. VNA suppot works in Quisk.
