### ISSUE TITLE
Hardware: Measure and document proper current consumption in HL2

### ISSUE THREAD

**Issue by softerhardware** [softerhardware/Hermes-Lite2#20]
Stew observed variations in HL2 current usage. Look for these variations in my prototypes. Document what expected current consumption should be.

**Comment by kf5kog** [comment]
After loading LED .jic file power consumption dropped to a steady 100ma.

**Comment by softerhardware** [comment]
Beta2 build notes on wiki contains a table with current measurements.

**Comment by softerhardware** [comment]
On wiki.
