### ISSUE TITLE
Hardware:  Static protection for Q1

### ISSUE THREAD

**Issue by jimahlstrom** [softerhardware/Hermes-Lite2#28]
Add a 10 uF capacitor to the input of Q1.

**Comment by in3otd** [comment]
and/or a TVS like [this](https://www.digikey.com/product-detail/en/epcos-tdk/B72530T140K62/495-7474-1-ND/6073151). I wonder if we should provide also some overvoltage protection (the input MOS is rated to 30 V); I don't think a TVS like this will be enough for non-transient overvoltages, though.

**Comment by softerhardware** [comment]
Change made in schematic. There is room for both capacitor and TVS device so footprints for both are planned. Best build TBD.

**Comment by softerhardware** [comment]
In schematic, footprints on PCB. BOM will pick up info from schematic. TVS was moved to before fuse.
