### ISSUE TITLE
Hardware: U18 configured as followers

### ISSUE THREAD

**Issue by jimahlstrom** [softerhardware/Hermes-Lite2#33]
The diodes D8, D9, D10 and D11 are removed, and U18 is configured as four followers.

**Comment by jimahlstrom** [comment]
Maybe diodes D10 and D11 should remain.  They are used for AIN1 and AIN2, and the forward and reverse power is probably measured with diodes.  If so, D10 and D11 will provide some diode drop compensation.

**Comment by softerhardware** [comment]
Beta3 schematic updated. 2 channels for temp and current are followers.

**Comment by softerhardware** [comment]
Done on PCB.
