### ISSUE TITLE
Hardware: Bidirectional TVS symbol is misleading

### ISSUE THREAD

**Issue by in3otd** [softerhardware/Hermes-Lite2#72]
The symbol for the SMBJ18CA (D12) and  the CDSOD323-T05LC  (D1) are a bit misleading, they should represent two diodes in "antiseries", like [here](http://www.littelfuse.com/~/media/electronics/datasheets/tvs_diodes/littelfuse_tvs_diode_smbj_datasheet.pdf.pdf).
BTW, I'm not sure that D12 should be a bidirectional diode, even if negative voltages will be blocked by Q1, maybe we could use an unidirectional protection there.

**Comment by softerhardware** [comment]
http://datasheet.octopart.com/CDSOD323-T05LC-Bourns-datasheet-13385636.pdf is slightly different.

**Comment by in3otd** [comment]
yes and maybe closer to the actual internal design but the complete circuit does not fit well in a schematic symbol :grin: . My point was that the current symbol looks like two Schottky diodes in antiparallel so at a first glance it appears to conduct at around &pm;400 mV

**Comment by softerhardware** [comment]
Schematic symbols updated to match datasheets.
