### ISSUE TITLE
Add this transformer info to the wiki

### ISSUE THREAD

**Issue by W9JSW** [softerhardware/Hermes-Lite2#79]
Pin 2 is the one in the center. Pins 1 and 3 face the LDMOS transistors, towards the edge of the board. Pins 4 and 5 face the center of the board, towards the opamp. For the 1T+1T, these are two single loops (once through the core each) from pin 1 to 2, and another from pin 3 to 2. I usually use two short wires. For the 4T, this is 4 times through the core from pins 4 to 5. There are no unusual crossings and the wires coming out of the core should go nicely to the respective pins. Only the wires going to pin 2 may need a little flexing.

**Comment by softerhardware** [comment]
Added to wiki. See https://github.com/softerhardware/Hermes-Lite2/wiki/Hermes-Lite-2.0-Getting-Started#transformer-pin-out
