### ISSUE TITLE
CN4 (SJ1-3525N) Will not sit flat on PCB

### ISSUE THREAD

**Issue by kf5kog** [softerhardware/Hermes-Lite2#80]
This part will not sit flat on PCB.  Based on mechanical drawing is shows a cutout required  for the round section of jack.  There are 2 other possible solutions.  Find a different part or remove the alignment pin holes so the jack will sit on those pins.  This will allow clearance for the jack housing.  I just filed a flat spot on the bottom plastic.  The round metal edge doesn't require filing, just the plastic area just behind it.
![cn4 jack](https://user-images.githubusercontent.com/8203042/35113796-bcd06996-fc50-11e7-815a-7e727d000216.jpg)

**Comment by softerhardware** [comment]
Added board cutout in hl2b6, 2/18/2018.
